# Numpy array and basics

In [2]:
import numpy as np

### Creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List v numpy

In [8]:
py_list = [1, 2, 3, 4, 5]
print("List multiplication by 2:", py_list * 2)

np_arr = np.array([1, 2, 3, 4, 5]) #element-wise multiplication
print("Numpy array multiplication by 2:", np_arr * 2)

import time 

start_time = time.time()
py_list = [i*2 for i in range (1000000)]
print("List operation time:", time.time() - start_time)

start_time = time.time()
np_arr = np.array([i*2 for i in range (1000000)])
print("Numpy array operation time:", time.time() - start_time)

List multiplication by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication by 2: [ 2  4  6  8 10]
List operation time: 0.1024017333984375
Numpy array operation time: 0.11255741119384766


### Array creation from scratch

In [15]:
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((2,2))
print(ones)

full = np.full((2,2),10)
print(full)

random = np.random.random((3,3))
print(random)

sequence = np.arange(0,11,2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]]
[[0.26933856 0.63163054 0.1088008 ]
 [0.69861868 0.425211   0.66843139]
 [0.2892294  0.4603321  0.59489062]]
[ 0  2  4  6  8 10]


### Vector, matrix, tensor

In [24]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])
tensor = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Arrayn properties

In [25]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Data type", arr.dtype)
print("Size", arr.size)

Shape (2, 3)
Dimension 2
Data type int64
Size 6


## Array reshaping

In [32]:
arr=np.arange(1,10)
print("Original ", arr)

reshape = arr.reshape(3,3)
print(reshape)

flattened = reshape.flatten()
print(flattened)

#returns view instead of copy
raveled = reshape.ravel()
print(raveled)

transposed = reshape.T
print(transposed)


Original  [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
