## Numpy array ops

In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing :", arr[1:7])
print("Stepping: ", arr[1:7:2])
print("Negative marking:", arr[-3])


Basic slicing : [2 3 4 5 6 7]
Stepping:  [2 4 6]
Negative marking: 8


In [10]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n", arr_2d)
print("Entire row (middle row)", arr_2d[1])
print("Entire column (middle column)", arr_2d[:,1])

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Entire row (middle row) [4 5 6]
Entire column (middle column) [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([4,1,3,2])
sorted = np.sort(unsorted)
print("Unsorted array:", unsorted , "\nSorted array:", sorted)
#In 2D array sorting, axis=0 sorts each column, and axis=1 sorts each row independently.

Unsorted array: [4 1 3 2] 
Sorted array: [1 2 3 4]


## Filtering

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even_array = arr[arr%2 == 0]
print("Even array: ", even_array)

Even array:  [ 2  4  6  8 10]


In [16]:
#Filtering with mask
mask = arr>5
masked_array = arr[mask]
print(masked_array)

[ 6  7  8  9 10]


## Fancy indexing ---- np.where() conditions

In [17]:
indices = [0,2,4]
print (arr[indices])

[1 3 5]


In [20]:
where_res = np.where(arr>5)
print(arr[where_res])

[ 6  7  8  9 10]


In [ ]:
condition = np.where(arr>5, arr*2, arr/2)
print(condition)

# Above line is equivalent to:
# if(arr>5) arr*2
# else arr/2

[ 0.5  1.   1.5  2.   2.5 12.  14.  16.  18.  20. ]


## Add or remove data

In [26]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2))
print(arr3)
arr4=np.delete(arr3,2)
print(arr4)

[1 2 3 4 5 6]
[1 2 4 5 6]
